version: "3"
services:
  app:
    build: ./application
    links:
      - db
    ports:
      - "5000:5000"

  db:
    image: postgres:latest
    env_file: .env
    expose:
      - 5432
    volumes:
    - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql